- hosts: all
  roles:
    - role: preinstall
  gather_facts: yes
  any_errors_fatal: true
  tags: [preinstall]

- hosts: redis
  roles:
    - role: redis
  gather_facts: yes
  any_errors_fatal: true
  tags: [redis]

- hosts: haproxy
  roles:
    - role: haproxy
  gather_facts: yes
  any_errors_fatal: true
  tags: [haproxy]
